#!/usr/bin/env python3
# -*- coding: utf-8 -*-

START_STATE, QUESTION_1_STATE, QUESTION_2_STATE, FORK_STATE = range(4)
PART_1_QUESTION_1_STATE, PART_1_QUESTION_2_STATE, PART_1_QUESTION_3_STATE, PART_1_QUESTION_4_STATE = range(10, 14)
PART_2_QUESTION_1_STATE, PART_2_QUESTION_2_STATE, PART_2_QUESTION_3_STATE, PART_2_QUESTION_4_STATE, PART_2_QUESTION_5_STATE, PART_2_QUESTION_6_STATE, PART_2_QUESTION_7_STATE = range(20, 27)
PART_3_QUESTION_1_STATE, PART_3_QUESTION_2_STATE, PART_3_QUESTION_3_STATE, PART_3_QUESTION_4_STATE, PART_3_QUESTION_4_1_STATE, PART_3_QUESTION_4_2_STATE, PART_3_QUESTION_4_3_STATE, PART_3_QUESTION_5_STATE, PART_3_QUESTION_5_1_STATE, PART_3_QUESTION_5_2_STATE, PART_3_QUESTION_5_3_STATE, PART_3_QUESTION_6_STATE = range(30, 42)
PART_4_QUESTION_1_STATE, PART_4_QUESTION_2_STATE, PART_4_QUESTION_3_STATE, PART_4_QUESTION_4_STATE, PART_4_QUESTION_4_1_STATE, PART_4_QUESTION_4_2_STATE, PART_4_QUESTION_5_STATE, PART_4_QUESTION_6_STATE, PART_4_QUESTION_7_STATE, PART_4_QUESTION_8_STATE, PART_4_QUESTION_8_YES_1_STATE, PART_4_QUESTION_8_NO_1_STATE, PART_4_QUESTION_9_STATE, PART_4_QUESTION_10_STATE, PART_4_QUESTION_11_STATE, PART_4_QUESTION_12_STATE,  = range(50, 66)
SURVEY_FINISH_STATE, PLANS_INFO_STATE, TOTAL_FINISH_STATE = range(70, 73)
ADMIN_STATE, ADMIN_USERNAME_LIST_STATE, ADMIN_EXPORT_RESULT_STATE = range(80, 83)